version: "3"

services:
  springboot-app:
    image: app
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9090:8082"
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      MARIADB_DATABASE: miola
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: