apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miola-db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: miola-db

  template:
    metadata:
      labels:
        app: miola-db

    spec:
      containers:
        - name: mariadb
          image: mariadb:latest

          ports:
            - containerPort: 3306

          env:
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: database

            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: password

          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: miola-db

spec:
  selector:
    app: miola-db

  ports:
    - port: 3306
      targetPort: 3306