spring.application.name=SpringData_Rest
#spring.h2.console.enabled=true
#spring.datasource.platform=h2
#spring.datasource.url=jdbc:h2:mem:test

#spring.datasource.url=jdbc:mariadb://localhost:3306/springboot
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true

spring.datasource.url=jdbc:mariadb://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/miola
spring.datasource.username=${MYSQL_USER:sa}
spring.datasource.password=${MYSQL_PASSWORD:azerty}

spring.jpa.hibernate.ddl-auto=update
server.port=8082

spring.data.rest.base-path=/api